version: "3.9"

services:
  build:
    image: devkit/tesla
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /build
    volumes:
      - .:/build
    command: make all
  clean:
    image: devkit/tesla
    working_dir: /build
    volumes:
      - .:/build
    command: make clean